### PR TITLE
Merge switchboard integration into realtime audio

### PR DESCRIPTION
**Pull request by jprx**
Bringing realtime audio up to date with latest ILLIXR integration.

### CODE REVIEW

**Comment by charmoniumQ** [comment]
Is this the version of audio pipeline whose commit hash is in `ILLIXR/configs/core_plugins.yaml`?

**Comment by jprx** [comment]
Yes, this is the commit from `core_plugins.yaml` and I confirmed it by checking against `.cache/paths/`

**Comment by charmoniumQ** [comment]
Apparently some merge conflicts. I'll do a last pass once those are resolved.

**Review by e3m3 — APPROVED** [review]

**Comment by mhuzai** [comment]
Accomplished via #6.

**Pull request closed without merging**
